title: Character Sheets
markdown: kramdown
domain: dnd.gimbaro.dev
url: https://dnd.gimbaro.dev

# for atom feed
author:
  name: Gamberi Elia
  email: gamberielia@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
