title: D&D Sheets
markdown: kramdown
domain: dnd.gimbaro.dev
github: https://github.com/Gimbardo/dnd_markdown
url: https://dnd.gimbaro.dev

# for atom feed
author:
  name: Gamberi Elia
  email: me@gimbaro.dev

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  sheets:
    output: true
  oneshots:
    output: true

defaults:
  - scope:
      path: "_sheets"
    values:
      layout: "post"
      permalink: /:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
