services:
  jekyll:
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      - JEKYLL_ENV=development
    command: "bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling"
